// FAQ generali e FAQ sui prezzi.
import type { QA } from '../fr/faq';

export type { QA } from '../fr/faq';

export const FAQ_GENERAL: QA[] = [
  { q: 'Come funziona l’assistente telefonico AI?', a: 'Configura un agente vocale con le Sue informazioni, le Sue regole e il Suo tono. L’agente risponde alle chiamate in entrata, effettua le chiamate in uscita autorizzate, qualifica le richieste, prenota gli appuntamenti e Le invia un riepilogo di ogni conversazione.' },
  { q: 'Quanto tempo serve per iniziare?', a: 'Un primo agente è pronto in pochi minuti a partire dalle Sue informazioni. Per una configurazione completa (calendario, numeri, trasferimenti) servono in genere uno o due giorni, con il nostro supporto.' },
  { q: 'Servono competenze tecniche?', a: 'No. Lei descrive la Sua attività, l’assistente per i prompt La guida e noi La aiutiamo con la telefonia e le integrazioni.' },
  { q: 'Cosa succede se l’agente non sa rispondere?', a: 'Non inventa: annota la richiesta, propone una richiamata o trasferisce la chiamata al Suo team secondo le regole che ha stabilito.' },
  { q: 'L’agente può gestire più chiamate contemporaneamente?', a: 'Sì. Più chiamate vengono gestite in parallelo sulla stessa linea: i Suoi clienti non restano più in attesa.' },
  { q: 'In cosa si differenzia da una segreteria telefonica o da un centralino tradizionale?', a: 'Una segreteria registra, un centralino smista. L’agente AI è un assistente telefonico intelligente: comprende la richiesta, pone le domande utili, agisce (appuntamento, richiamata, risposta) e Le invia una scheda pronta da usare.' },
  { q: 'Posso usare il mio sistema telefonico o il mio centralino virtuale attuale?', a: 'Sì. Può inoltrare la Sua linea attuale all’agente, collegare il Suo centralino o il Suo operatore tramite SIP, oppure importare i Suoi numeri Twilio e Telnyx.' },
  { q: 'Posso collegare il mio calendario?', a: 'Sì: Google Calendar, Outlook, Cal.com e Calendly. L’agente propone gli orari liberi e prenota direttamente: le prenotazioni telefoniche diventano automatiche.' },
  { q: 'Posso modificare i prompt?', a: 'Sì. L’editor di prompt Le permette di impostare l’obiettivo, il tono, le domande e i limiti dell’agente, con una guida passo passo e senza competenze tecniche.' },
  { q: 'Posso creare scenari senza codice?', a: 'Sì, con il flow builder a partire dal piano Assistant: concatena trigger e azioni con il drag and drop, collegati a oltre 300 strumenti.' },
  { q: 'Posso usare WhatsApp e Instagram?', a: 'Sì, su tutti i piani: SMS, WhatsApp, Messenger e Instagram, con cronologia centralizzata. I messaggi si pagano con i crediti messaggi; i follow-up automatici richiedono il piano Assistant.' },
  { q: 'Fornite numeri di telefono?', a: 'Sì, come opzione: un numero dedicato si acquista dalla Sua area clienti e si paga ogni mese, oltre al piano (a partire da 5,99 $ IVA esclusa al mese, a seconda del paese; il prezzo esatto viene mostrato prima dell’acquisto). Paesi disponibili all’acquisto: Stati Uniti, Canada, Regno Unito, Australia, Italia, Paesi Bassi, Polonia, Danimarca, Finlandia, Romania, Israele, Sudafrica. Per un numero di un altro paese, o per mantenere il Suo: inoltro di chiamata, importazione da Twilio o Telnyx, oppure connessione SIP.' },
  { q: 'Posso usare SIP?', a: 'Sì, su tutti i piani. La guidiamo nel collegamento del Suo trunk SIP o del Suo centralino.' },
  { q: 'Come caricate le informazioni della mia azienda?', a: 'Aggiunge i Suoi documenti PDF, le pagine del Suo sito o le Sue procedure nella base di conoscenza. L’agente le consulta durante la chiamata.' },
  { q: 'È conforme al GDPR?', a: 'La piattaforma offre gli strumenti necessari: consenso, lista di esclusione, periodo di conservazione configurabile, cancellazione dei dati e controllo degli accessi. La configurazione e le informative restano da adattare alla Sua attività; La accompagniamo in questo.' },
  { q: 'Come funziona la prova gratuita?', a: 'Crea il Suo account, poi sceglie il piano da provare: i primi 14 giorni sono gratuiti, con 30 minuti di chiamate inclusi. All’attivazione è richiesta una carta, ma durante la prova non viene addebitato nulla. Se annulla prima della fine dei 14 giorni, non paga nulla.' },
  { q: 'L’area clienti è in italiano?', a: 'L’interfaccia dell’area clienti è in inglese. Un’assistente di supporto integrata La guida nella Sua lingua, italiano compreso, per iscritto o a voce, e la pagina Aiuto dell’area clienti traduce ogni menu e illustra passo passo le operazioni più comuni.' },
  { q: 'Chi mi richiama quando lascio il mio numero?', a: 'La nostra assistente vocale AI La richiama in orario d’ufficio per capire le Sue esigenze e mostrarLe una demo; se lo desidera, subentra un consulente. Può chiedere in qualsiasi momento di non essere più richiamato.' },
  { q: 'L’agente si presenta come un’AI?', a: 'Sì. L’agente si presenta in modo trasparente come assistente AI e può trasferire la chiamata a una persona quando Lei lo ha previsto.' },
];

export const FAQ_PRICING: QA[] = [
  { q: 'Posso pagare a consumo, senza piano?', a: 'Sì. Crei il Suo account, poi aggiunga credito quando vuole (Add credits): il minuto costa 0,39 $ IVA esclusa, senza abbonamento, e il credito non scade. Ha le stesse funzioni del piano Receptionist (1 agente, 2 chiamate simultanee, 1 numero). Appena le chiamate sono regolari, un piano costa meno: da 0,28 $ a 0,22 $ al minuto.' },
  { q: 'Cosa succede dopo i 30 minuti di prova?', a: 'I 30 minuti sono il limite del periodo di prova: una volta raggiunti, le chiamate si interrompono fino alla fine della prova o fino all’avvio del Suo abbonamento. Al termine dei 14 giorni parte il piano scelto, a meno che non lo abbia annullato dalla Sua area clienti.' },
  { q: 'I prezzi sono IVA esclusa?', a: 'Sì, tutti i prezzi sono indicati IVA esclusa. Le imposte locali si aggiungono se applicabili.' },
  { q: 'Cosa succede se supero i miei minuti?', a: 'Può aggiungere minuti in qualsiasi momento con una ricarica, per coprire un mese più intenso. Se li supera regolarmente, il piano superiore costa meno al minuto: glielo segnaliamo.' },
  { q: 'Il numero di telefono è incluso nel piano?', a: 'No. Il piano comprende i minuti e le funzioni; un numero dedicato è un’opzione a pagamento mensile, a partire da 5,99 $ IVA esclusa al mese a seconda del paese, al prezzo mostrato prima dell’acquisto. Può anche usare il Suo numero attuale senza costi da parte nostra: inoltro di chiamata (il Suo operatore potrebbe addebitare l’inoltro verso un numero estero), importazione da Twilio o Telnyx, oppure SIP.' },
  { q: 'Posso usare il mio numero?', a: 'Sì, su tutti i piani: inoltro di chiamata, importazione da Twilio o Telnyx, oppure connessione SIP.' },
  { q: 'Avete una demo dal vivo?', a: 'Sì. Può parlare con l’agente dal Suo browser o chiedere di essere richiamato per una dimostrazione.' },
  { q: 'Perché una ricarica costa di più al minuto rispetto a un piano?', a: 'La ricarica serve per esigenze occasionali. Il piano resta la soluzione più conveniente per un volume regolare: più è grande, più il prezzo al minuto scende.' },
  { q: 'Come vengo fatturato?', a: 'L’abbonamento viene addebitato in anticipo sulla Sua carta, ogni mese o ogni anno secondo la fatturazione scelta, alla data di rinnovo, e la fattura è disponibile nella Sua area clienti (Billing info). Le ricariche di minuti vengono fatturate al momento dell’acquisto. Le imposte sono calcolate automaticamente in base al Suo paese e al Suo status.' },
  { q: 'È prevista una fatturazione annuale?', a: 'Sì, per i tre piani a pagamento: con la fatturazione annuale ha 2 mesi gratis (paga 10 mesi e ne ottiene 12). L’anno viene pagato in anticipo, in un’unica soluzione. I minuti inclusi restano assegnati ogni mese, come con la fatturazione mensile, e le funzioni sono identiche; la tariffa per minuto extra non cambia. Può disdire in qualsiasi momento dalla Sua area clienti: la disdetta ha effetto alla fine dell’anno già pagato, senza rimborso del periodo residuo (Condizioni generali, articoli 3 e 4).' },
  { q: 'Come annullo il mio abbonamento?', a: 'Dalla Sua area clienti (Billing info), in qualsiasi momento e senza costi. Durante la prova, l’annullamento evita qualsiasi addebito. Dopo la prova, l’abbonamento resta attivo fino alla fine del periodo già pagato, poi si interrompe.' },
  { q: 'Posso cambiare piano?', a: 'Sì, in qualsiasi momento e senza vincoli. Passi al piano superiore quando il Suo volume cresce; la modifica viene mostrata prima della conferma.' },  { q: 'Cosa succede quando finiscono i miei minuti?', a: 'I minuti oltre il piano vengono pagati con il Suo credito. Senza credito, le chiamate si sospendono finché non effettua una ricarica o il Suo piano si rinnova il mese successivo. Riceve un avviso via email quando il saldo è basso e può attivare la ricarica automatica.' },
  { q: 'Cosa succede quando i miei minuti finiscono?', a: 'I minuti oltre il Suo piano vengono pagati con il Suo credito. Senza credito, le chiamate vengono sospese fino alla prossima ricarica o al rinnovo del piano il mese successivo. Riceve un avviso via email quando il saldo è basso e può attivare la ricarica automatica.' },
  { q: 'Il trasferimento di chiamata al mio team è a pagamento?', a: 'Il trasferimento è incluso in tutti i piani, senza costi per singolo trasferimento. L’agente passa la chiamata al Suo team secondo le Sue regole; finché la chiamata trasferita prosegue, la sua durata viene scalata dai Suoi minuti, come il resto della chiamata. Il trasferimento si imposta in «Tools & actions» dell’agente.' },
  { q: 'A cosa servono i crediti messaggi?', a: 'Pagano gli scambi scritti: risposte dell’AI su WhatsApp, SMS, Messenger e chat del sito, e messaggi inviati. 100 crediti valgono 1 $; una risposta scritta dell’AI costa circa 2 crediti, un SMS o un modello WhatsApp dipende dal paese. Assistant include 1.000 crediti al mese (≈ 500 risposte), Call Center 3.000 (≈ 1.500). Con Receptionist questi canali sono disponibili e Lei aggiunge credito secondo l’uso (Add credits).' },
];
