// General FAQ and pricing FAQ.
import type { QA } from '../fr/faq';

export type { QA } from '../fr/faq';

export const FAQ_GENERAL: QA[] = [
  { q: 'How does an AI receptionist work?', a: 'You set up a voice agent with your information, your rules and your tone. It answers inbound calls, makes authorised outbound calls, qualifies enquiries, books appointments and sends you a summary of every conversation.' },
  { q: 'How long does it take to get started?', a: 'A first agent is ready in a few minutes from your information. For a full setup (calendar, numbers, transfers), allow one to two days in most cases, with our help.' },
  { q: 'Do I need technical skills?', a: 'No. You describe your business, the prompt assistant guides you, and we help with telephony and integrations.' },
  { q: 'What happens if the agent doesn’t know the answer?', a: 'It doesn’t make one up: it notes the request, offers a callback or transfers to your team, following the rules you have set.' },
  { q: 'Can the agent handle several calls at once?', a: 'Yes. Unlike a single human receptionist, the AI answering service handles several calls in parallel on the same line, so your customers no longer wait.' },
  { q: 'How is this different from voicemail or a traditional phone system?', a: 'Voicemail records, a phone system routes. An AI receptionist understands the request, asks the right questions, takes action (appointment, callback, answer) and sends you a record you can act on.' },
  { q: 'Can I use my existing phone system?', a: 'Yes. You can forward your current line to the agent, connect your phone system or carrier via SIP, or import your Twilio and Telnyx numbers.' },
  { q: 'Can I connect my calendar?', a: 'Yes: Google Calendar, Outlook and others, through Cal.com or Calendly. The agent offers free slots and books directly.' },
  { q: 'Can I edit the prompts?', a: 'Yes. The prompt editor lets you set the agent’s goal, tone, questions and limits, step by step, with no technical expertise.' },
  { q: 'Can I build scenarios without code?', a: 'Yes, with the no-code automation platform, from the Assistant plan upwards: you chain triggers and actions by drag and drop, connected to over 300 tools.' },
  { q: 'Can I use WhatsApp and Instagram?', a: 'Yes, on every plan: SMS, WhatsApp, Messenger and Instagram, with a single message history. Messages are paid for with message credits; automated follow-ups require the Assistant plan.' },
  { q: 'Can I message you on WhatsApp?', a: 'Yes, on +33 7 45 46 04 46 (https://wa.me/33745460446). Our own AI agent replies 24/7, in English, French, Italian, Polish, Dutch or Hebrew: it answers your questions, sends you the right links and can arrange a callback. It’s a live preview of what your agent will do for your customers on WhatsApp.' },
  { q: 'Do you provide phone numbers?', a: 'Yes, as an option: a dedicated number is bought from your customer area and paid monthly, on top of your plan (from $5.99 excl. VAT/tax per month depending on the country; the exact price is shown before you buy). Countries available to buy: United States, Canada, United Kingdom, Australia, Italy, Netherlands, Poland, Denmark, Finland, Romania, Israel, South Africa. For a country not listed, or to keep your own number: call forwarding, Twilio or Telnyx import, or a SIP connection.' },
  { q: 'Can I use SIP?', a: 'Yes, on every plan. We guide you through connecting your SIP trunk or phone system.' },
  { q: 'How do you load my business information?', a: 'You add your PDF documents, website pages or procedures to the knowledge base. The agent refers to them during the call.' },
  { q: 'Does it comply with data protection law?', a: 'The platform provides the tools you need: consent, an exclusion list, configurable retention, data deletion and access control. Your setup and privacy notices still need to fit your business; we help you with that.' },
  { q: 'How does the free trial work?', a: 'You create your account, then choose the plan you want to try: the first 14 days are free, with 30 minutes of calls included. A card is required on activation but nothing is charged during the trial. Cancel before the 14 days are up and you pay nothing.' },
  { q: 'What language is the customer area in?', a: 'The customer area interface is in English. A built-in help assistant answers in your language, in writing or out loud, and the Help page of the customer area explains each menu and walks you through common tasks step by step.' },
  { q: 'Who calls me back when I leave my number?', a: 'Our AI voice assistant calls you back during business hours to understand what you need and give you a demo; an adviser takes over if you wish. You can ask not to be called again at any time.' },
  { q: 'Does the agent say it is an AI?', a: 'Yes. The agent is honestly presented as an AI assistant, and can transfer to a person when you have set it up to do so.' },
  { q: 'My customers prefer talking to a person. Is that a problem?', a: 'Most calls are predictable: opening hours, prices, availability, bookings. The agent handles them straight away, at any hour. For a sensitive request, an unhappy caller or someone who wants to speak to your team, it transfers the call if you have set that up, or arranges a callback with a summary of the request.' },
  { q: 'Does it sound like a robot?', a: 'The easiest way to find out is to hear it: start the live demo from your browser or have it ring your own phone. The voices are native in each language, the agent can be interrupted and it replies without awkward pauses. Thirty seconds is enough to make up your mind.' },
  { q: 'I already have a receptionist or an answering service. Why would I need this?', a: 'A traditional answering service mostly takes messages. The agent answers questions, books straight into your calendar, qualifies the enquiry and handles several calls at once. Many customers keep it alongside their team: it takes over at peak times, over lunch, in the evening and at weekends.' },
  { q: 'My engineers are on site all day. How does that work?', a: 'That is exactly what it is built for. The agent answers for you, gets the details (fault, address, urgency, preferred slot) and sends you a complete job sheet. You call back when you are free, with all the information to hand.' },
  { q: 'We tried an AI a few years ago and it wasn’t convincing. What has changed?', a: 'Voices, understanding and response speed are a generation ahead: the agent understands natural speech, adapts when interrupted and follows your instructions. The best way to judge is to try the live demo, then the 14-day free trial on your own calls.' },
  { q: 'What should the agent never do?', a: 'You decide. In its instructions, you list what it must not promise or discuss: priced quotes, guarantees, diagnoses, legal or financial advice. It then passes those topics to your team, with a summary.' },
];

export const FAQ_PRICING: QA[] = [
  { q: 'Can I pay as I go, without a plan?', a: 'Yes. Create your account, then add credit whenever you like (Add credits): calls cost $0.39 excl. tax per minute, with no subscription, and credit never expires. You get the same features as the Receptionist plan (1 agent, 2 concurrent calls, 1 optional dedicated number). As soon as your calls are regular, a plan costs less: from $0.28 down to $0.22 a minute.' },
  { q: 'What happens after the 30 trial minutes?', a: 'The 30 minutes are the cap for the trial period: once reached, calls stop until the trial ends or until you start your subscription. At the end of the 14 days, your chosen plan starts, unless you have cancelled it from your customer area.' },
  { q: 'Are prices excl. tax?', a: 'Yes, all prices are shown excluding tax. Local taxes are added where they apply.' },
  { q: 'What happens if I go over my minutes?', a: 'You can add minutes at any time with a top-up, to cover a busy month. If you regularly go over, the next plan up works out cheaper per minute: we will let you know.' },
  { q: 'Is a phone number included in the plan?', a: 'No. The plan covers minutes and features; a dedicated number is an option paid monthly, from $5.99 excl. VAT/tax depending on the country, at the price shown before you buy. You can also use your current number at no charge from us: call forwarding (your carrier may charge for forwarding to an overseas number), Twilio or Telnyx import, or SIP.' },
  { q: 'Can I use my own number?', a: 'Yes, on every plan: call forwarding, Twilio or Telnyx import, or a SIP connection.' },
  { q: 'Do you have a live demo?', a: 'Yes. You can talk to the agent from your browser or ask for a callback for a demo.' },
  { q: 'Why does a top-up cost more per minute than a plan?', a: 'A top-up is there for occasional extra needs. A plan remains the most economical option for regular volume: the bigger the plan, the lower the price per minute.' },
  { q: 'How am I billed?', a: 'Your subscription is charged to your card in advance, every month or every year depending on the billing you choose, on the same date, and the invoice is available in your customer area (Billing info). Minute top-ups are billed when you buy them. Taxes are calculated automatically based on your country and status.' },
  { q: 'Is there annual billing?', a: 'Yes, on all three paid plans: annual billing gives you 2 months free (you pay for 10 months and get 12). The year is paid upfront, in a single payment. Your included minutes are still allocated every month, just as on monthly billing, and the features are exactly the same; the extra-minute rate does not change. You can cancel at any time from your customer area: cancellation takes effect at the end of the year already paid for, with no refund of the remaining period (Terms, Articles 3 and 4).' },
  { q: 'How do I cancel my subscription?', a: 'From your customer area (Billing info), at any time and free of charge. During the trial, cancelling avoids any charge. After the trial, your subscription stays active until the end of the period already paid for, then stops.' },
  { q: 'Can I change plan?', a: 'Yes, at any time and with no commitment. Move up a plan when your volume grows; the change is shown before you confirm.' },
  { q: 'What happens when my minutes run out?', a: 'Minutes beyond your plan are paid from your credit. Without credit, calls pause until you top up or your plan renews next month. You get an email alert when your balance runs low, and you can turn on automatic top-up.' },
  { q: 'Is transferring a call to my team charged?', a: 'Call transfer is included on every plan, with no per-transfer fee. The agent hands the call to your team according to your rules; while the transferred call goes on, its duration is counted in your minutes, like the rest of the call. You set up the transfer in the agent’s “Tools & actions”.' },
  { q: 'What are message credits for?', a: 'They pay for written exchanges: AI replies on WhatsApp, SMS, Messenger and website chat, and messages you send. 100 credits are worth $1; a written AI reply costs about 2 credits, an SMS or a WhatsApp template depends on the country. Assistant includes 1,000 credits a month (≈ 500 replies), Call Centre 3,000 (≈ 1,500). On Receptionist these channels are available and you add credit as you use them (Add credits).' },
  { q: 'Is there a setup fee?', a: 'No. No installation or setup fee and no commitment: you pay for the plan you choose (or per minute on pay as you go), plus a dedicated number only if you take one.' },
  { q: 'How much does a call cost?', a: 'A 5-minute call costs about $1.95 excl. tax on pay as you go ($0.39 per minute). On a plan, the real price per minute is lower: about $0.28 on Receptionist, $0.25 on Assistant and $0.22 on Call Centre, so roughly $1.10 to $1.40 for the same call.' },
];
