// Algemene FAQ en FAQ over tarieven.
import type { QA } from '../fr/faq';

export type { QA };

export const FAQ_GENERAL: QA[] = [
  { q: 'Hoe werkt de AI-telefoonassistent?', a: 'U stelt een spraakagent in met uw gegevens, uw regels en uw toon. De agent neemt inkomende gesprekken aan, voert toegestane uitgaande gesprekken, kwalificeert aanvragen, plant afspraken in en stuurt u van elk gesprek een samenvatting.' },
  { q: 'Hoe snel kan ik beginnen?', a: 'Een eerste virtuele receptionist staat binnen enkele minuten klaar op basis van uw gegevens. Voor een volledige configuratie (agenda, nummers, doorverbinden) rekent u meestal op één tot twee dagen, met onze begeleiding.' },
  { q: 'Heb ik technische kennis nodig?', a: 'Nee, ook niet als zzp’er zonder IT-afdeling. U beschrijft uw bedrijf, de promptassistent begeleidt u en wij helpen u met de telefonie en de integraties.' },
  { q: 'Wat gebeurt er als de agent het antwoord niet weet?', a: 'Hij verzint niets: hij noteert de vraag, biedt aan om terug te bellen of verbindt door met uw team, volgens de regels die u hebt ingesteld.' },
  { q: 'Kan de agent meerdere gesprekken tegelijk afhandelen?', a: 'Ja. Meerdere gesprekken worden tegelijk afgehandeld op dezelfde lijn: uw klanten hoeven niet meer te wachten en uw telefonische bereikbaarheid blijft op peil, ook op drukke momenten.' },
  { q: 'Wat is het verschil met een voicemail, telefoonbeantwoorder of telefooncentrale?', a: 'Een voicemail of gewone telefoonbeantwoorder neemt een bericht op, een telefooncentrale verbindt door. De AI-telefoonbeantwoorder begrijpt de vraag, stelt de juiste vragen, onderneemt actie (afspraak, terugbelverzoek, antwoord) en stuurt u een bruikbaar overzicht.' },
  { q: 'We hebben al een keuzemenu (IVR). Wat voegt de agent toe?', a: 'Met de agent spreekt de beller gewoon, zonder “toets 1”: de vraag wordt begrepen en afgehandeld (antwoord, afspraak, terugbelverzoek), niet alleen doorgestuurd. U kunt de agent vóór uw keuzemenu plaatsen, het menu ermee vervangen of hem achter een van de keuzes zetten, via doorschakelen of SIP. Bij het doorverbinden kan de agent ook cijfers intoetsen (DTMF-tonen) om door een menu te navigeren of een toestel te bereiken.' },
  { q: 'Kan ik mijn bestaande telefoonsysteem gebruiken?', a: 'Ja. U kunt uw huidige lijn doorschakelen naar de agent, uw telefooncentrale of provider via SIP koppelen, of uw Twilio- en Telnyx-nummers importeren.' },
  { q: 'Kan ik afspraken laten inplannen via de telefoon?', a: 'Ja: koppel Cal.com of Calendly, die zelf verbonden zijn met uw Google Agenda of Outlook. De agent stelt vrije tijdsloten voor en boekt direct in uw agenda.' },
  { q: 'Kan ik de prompts aanpassen?', a: 'Ja. Met de prompteditor stelt u het doel, de toon, de vragen en de grenzen van de agent in, stap voor stap begeleid en zonder technische kennis.' },
  { q: 'Kan ik scenario’s maken zonder code?', a: 'Ja, met de no-code automatiseringen vanaf het Assistent-abonnement: u koppelt triggers en acties via slepen en neerzetten, verbonden met meer dan 300 tools.' },
  { q: 'Kan ik WhatsApp en Instagram gebruiken?', a: 'Ja, in alle abonnementen: sms, WhatsApp, Messenger en Instagram, met een centrale geschiedenis. Berichten worden betaald met berichtcredits; automatische opvolging vraagt het Assistent-abonnement.' },
  { q: 'Kan ik u een WhatsApp sturen?', a: 'Ja, naar +33 7 45 46 04 46 (https://wa.me/33745460446). Onze eigen AI-agent antwoordt 24/7, in het Nederlands, Engels, Frans, Italiaans, Pools of Hebreeuws: hij beantwoordt uw vragen, stuurt u de juiste links en kan een terugbelafspraak regelen. Zo ziet u live wat uw agent voor uw klanten op WhatsApp zal doen.' },
  { q: 'Leveren jullie telefoonnummers?', a: 'Ja, als optie: een eigen nummer koopt u in uw klantomgeving en betaalt u per maand, bovenop het abonnement (vanaf $ 3,99 excl. btw per maand, afhankelijk van het land; de exacte prijs ziet u vóór de aankoop). Landen waarvoor u een nummer kunt kopen: Verenigde Staten, Canada, Verenigd Koninkrijk, Australië, Italië, Nederland, Polen, Denemarken, Finland, Roemenië, Israël, Zuid-Afrika. Voor een nummer uit een ander land, of om uw eigen nummer te behouden: doorschakelen, import via Twilio of Telnyx, of een SIP-koppeling.' },
  { q: 'Kan ik SIP gebruiken?', a: 'Ja, in alle abonnementen. Wij begeleiden u bij het koppelen van uw SIP-trunk of telefooncentrale.' },
  { q: 'Hoe laadt u de gegevens van mijn bedrijf?', a: 'U voegt uw pdf-documenten, de pagina’s van uw website of uw procedures toe aan de kennisbank. De agent raadpleegt deze tijdens het gesprek.' },
  { q: 'Voldoet het aan de AVG?', a: 'Het platform biedt de benodigde hulpmiddelen: toestemming, uitsluitingslijst, instelbare bewaartermijn, verwijdering van gegevens en toegangsbeheer. De gegevens worden gehost in de Europese Economische Ruimte en/of de Verenigde Staten, met passende waarborgen (modelcontractbepalingen of het Data Privacy Framework), en de verwerkersovereenkomst (DPA) is opgenomen in de voorwaarden (artikel 8), met een ondertekende versie op aanvraag. Uw configuratie en uw privacyverklaringen moet u nog afstemmen op uw bedrijf; wij helpen u daarbij.' },
  { q: 'Hoe werkt de gratis proefperiode?', a: 'U maakt uw account aan en kiest het abonnement dat u wilt testen: de eerste 14 dagen zijn gratis, met 30 belminuten inbegrepen. Bij activering wordt om een creditcard gevraagd, maar tijdens de proefperiode wordt niets afgeschreven. Zegt u op vóór het einde van de 14 dagen, dan betaalt u niets. 7 dagen vóór het einde van de proefperiode ontvangt u een herinneringsmail.' },
  { q: 'Is de klantomgeving in het Nederlands?', a: 'De interface van de klantomgeving is in het Engels. Een ingebouwde hulpassistent helpt u verder in uw eigen taal, dus ook in het Nederlands, schriftelijk of gesproken, en de Help-pagina van de klantomgeving vertaalt elk menu en legt de meest voorkomende taken stap voor stap uit.' },
  { q: 'Wie belt mij terug als ik mijn nummer achterlaat?', a: 'Onze AI-spraakassistent belt u tijdens kantooruren terug om uw situatie door te nemen en u een demonstratie te geven; als u dat wilt, neemt een adviseur het over. U kunt op elk moment aangeven dat u niet meer gebeld wilt worden.' },
  { q: 'Stelt de agent zich voor als AI?', a: 'Ja. Aan het begin van elk gesprek meldt de agent dat de beller met een AI-assistent spreekt, zoals de Europese AI-verordening (art. 50) vereist. Als u dat hebt ingesteld, verbindt hij door naar een medewerker.' },
  { q: 'Mijn klanten praten liever met een mens: is dat een probleem?', a: 'De meeste gesprekken zijn voorspelbaar: openingstijden, prijzen, beschikbaarheid, afspraken maken. De agent handelt ze meteen af, op elk uur. Bij een gevoelige vraag, een ontevreden beller of iemand die uw team wil spreken, verbindt hij door als u dat hebt ingesteld, of plant hij een terugbelverzoek met een samenvatting van de vraag.' },
  { q: 'Klinkt het als een robot?', a: 'Het makkelijkst is om het zelf te horen: start de live demo in uw browser of laat de agent uw eigen telefoon bellen. De stemmen klinken natuurlijk, ook in het Nederlands, de agent laat zich onderbreken en antwoordt zonder ongemakkelijke stiltes. Dertig seconden zijn genoeg om een oordeel te vormen.' },
  { q: 'Ik heb al een secretaresse of een telefoonservice: wat voegt het toe?', a: 'Een klassieke telefoonservice noteert vooral berichten. De agent beantwoordt vragen, boekt direct in uw agenda, kwalificeert de aanvraag en neemt meerdere gesprekken tegelijk aan. Veel klanten gebruiken hem als aanvulling: hij neemt het over bij drukte, in de lunchpauze, ’s avonds en in het weekend.' },
  { q: 'Mijn monteurs zijn de hele dag op pad: hoe werkt dat?', a: 'Precies daarvoor is het bedoeld. De agent neemt namens u op, vraagt door (storing, adres, spoed, gewenst tijdstip) en stuurt u een volledige samenvatting. U belt terug wanneer het u uitkomt, met alle informatie bij de hand.' },
  { q: 'We hebben een paar jaar geleden AI getest en dat viel tegen. Wat is er veranderd?', a: 'Stemmen, spraakbegrip en reactiesnelheid zijn een generatie verder: de agent begrijpt natuurlijke zinnen, past zich aan als u hem onderbreekt en volgt uw instructies. Oordeel zelf met de live demo, en daarna met de gratis proefperiode van 14 dagen op uw eigen gesprekken.' },
  { q: 'Wat mag de agent nooit doen?', a: 'Dat bepaalt u. In de instructies zet u wat hij niet mag beloven of bespreken: prijsopgaven, garanties, diagnoses, juridisch of financieel advies. Die onderwerpen verwijst hij dan door naar uw team, met een samenvatting.' },
];

export const FAQ_PRICING: QA[] = [
  { q: 'Kan ik per gebruik betalen, zonder abonnement?', a: 'Ja. Maak uw account aan en waardeer tegoed op wanneer u wilt (Add credits): een minuut kost $ 0,39 excl. btw, zonder abonnement, en tegoed vervalt niet. U krijgt dezelfde functies als het Receptionist-abonnement (1 agent, 2 gelijktijdige gesprekken, 1 eigen nummer mogelijk als optie, niet inbegrepen, vanaf $ 3,99 excl. btw per maand). Zodra u regelmatig gebeld wordt, is een abonnement goedkoper: van $ 0,28 tot $ 0,22 per minuut.' },
  { q: 'Wat gebeurt er na de 30 proefminuten?', a: 'De 30 minuten zijn het maximum van de proefperiode: zodra dat bereikt is, stoppen de gesprekken tot het einde van de proefperiode of tot u uw abonnement start. Na de 14 dagen start het gekozen abonnement, tenzij u het in uw klantomgeving hebt opgezegd.' },
  { q: 'Zijn de prijzen exclusief btw?', a: 'Ja, alle prijzen worden exclusief belastingen weergegeven. Lokale belastingen komen erbij als ze van toepassing zijn.' },
  { q: 'Wat gebeurt er als ik over mijn minuten heen ga?', a: 'U voegt op elk moment minuten toe met een opwaardering, voor een drukke maand. Gaat u er regelmatig overheen, dan is het grotere abonnement per minuut goedkoper: wij laten u dat weten.' },
  { q: 'Is het telefoonnummer inbegrepen in het abonnement?', a: 'Nee. Het abonnement omvat de minuten en de functies; een eigen nummer is een optie die u per maand betaalt, vanaf $ 3,99 excl. btw afhankelijk van het land, tegen de prijs die vóór de aankoop wordt getoond. U kunt ook uw huidige nummer gebruiken zonder kosten van onze kant: doorschakelen (uw provider kan kosten rekenen voor doorschakelen naar een buitenlands nummer), import via Twilio of Telnyx, of SIP.' },
  { q: 'Kan ik mijn eigen nummer gebruiken?', a: 'Ja, in alle abonnementen: doorschakelen, import via Twilio of Telnyx, of een SIP-koppeling.' },
  { q: 'Hebben jullie een live demo?', a: 'Ja. U kunt vanuit uw browser met de agent praten of vragen om teruggebeld te worden voor een demonstratie.' },
  { q: 'Waarom kost een opwaardering per minuut meer dan een abonnement?', a: 'De opwaardering is bedoeld voor een eenmalige piek. Het abonnement blijft de voordeligste oplossing voor een vast volume: hoe groter het abonnement, hoe lager de prijs per minuut.' },
  { q: 'Hoe word ik gefactureerd?', a: 'Het abonnement wordt vooraf van uw creditcard afgeschreven, elke maand of elk jaar afhankelijk van de gekozen facturatie, telkens op dezelfde datum, en de factuur staat in uw klantomgeving (Billing info). Opwaarderingen van minuten worden gefactureerd op het moment van aankoop. Belastingen worden automatisch berekend op basis van uw land en uw status.' },
  { q: 'Is er jaarlijkse facturatie?', a: 'Ja, voor de drie betaalde abonnementen: met jaarlijkse facturatie krijgt u 2 maanden gratis (u betaalt 10 maanden en krijgt er 12). Het jaar wordt vooraf in één keer betaald. De inbegrepen minuten worden nog steeds elke maand toegekend, net als bij maandelijkse facturatie, en de functies zijn identiek; het tarief per extra minuut verandert niet. U kunt op elk moment opzeggen via uw klantomgeving: de opzegging gaat in aan het einde van het reeds betaalde jaar, zonder terugbetaling van de resterende periode (algemene voorwaarden, artikelen 3 en 4).' },
  { q: 'Hoe zeg ik mijn abonnement op?', a: 'Op elk moment, via uw klantomgeving: onderdeel Billing info (facturatie), knop “Cancel subscription”. Opzeggen is kosteloos. Zegt u tijdens de proefperiode op vóór het einde van de 14 dagen, dan wordt er niets afgeschreven; 7 dagen vóór het einde van de proefperiode ontvangt u een herinneringsmail. Na de proefperiode blijft het abonnement actief tot het einde van de al betaalde periode en stopt het daarna.' },
  { q: 'Kan ik van abonnement wisselen?', a: 'Ja, op elk moment en zonder verplichtingen. Stap over op een groter abonnement wanneer uw volume groeit; de wijziging wordt getoond voordat u bevestigt.' },
  { q: 'Wat gebeurt er als mijn minuten op zijn?', a: 'Minuten boven uw abonnement worden betaald met uw tegoed. Zonder tegoed worden de gesprekken gepauzeerd tot u opwaardeert of uw abonnement volgende maand wordt verlengd. U krijgt een melding per e-mail wanneer uw saldo laag wordt, en u kunt automatisch opwaarderen inschakelen.' },
  { q: 'Kost het doorverbinden naar mijn team geld?', a: 'Doorverbinden is inbegrepen in elk abonnement, zonder kosten per doorverbinding. De agent geeft het gesprek door aan uw team volgens uw regels; zolang het doorverbonden gesprek loopt, gaat de duur van uw minuten af, net als de rest van het gesprek. U stelt het doorverbinden in bij “Tools & actions” van de agent.' },
  { q: 'Waarvoor dienen berichtcredits?', a: 'Hiermee betaalt u schriftelijk contact: AI-antwoorden in de websitechat, via WhatsApp, Messenger en Instagram, en verzonden berichten. Een schriftelijk AI-antwoord kost 3 credits, een WhatsApp-bericht dat binnen een sessie wordt ontvangen of verzonden 1,4 credits en een verzonden sms 2 credits (dit bedrag kan per provider of land verschillen); een WhatsApp-sjabloonbericht volgt het tarief van Meta per land en categorie, met toeslag, en WhatsApp-gesprekken worden in minuten gefactureerd. Elke maand bevat Assistent 1.000 credits (≈ 330 antwoorden) en Callcenter 3.000 (≈ 1.000); Receptionist bevat geen berichtcredits. Credits nodig? Zet minuten om in uw klantomgeving: 1 minuut = 9 credits. Bij 0 credits stoppen schriftelijke antwoorden en het verzenden van sms- en WhatsApp-berichten tot u opwaardeert.' },
  { q: 'Zijn er opstartkosten?', a: 'Nee. Geen installatie- of opstartkosten en geen verplichtingen: u betaalt het gekozen abonnement (of per minuut bij betalen per gebruik), en een eigen nummer alleen als u er een neemt.' },
  { q: 'Wat kost een gesprek?', a: 'Een gesprek van 5 minuten kost bij betalen per gebruik ongeveer $ 1,95 excl. btw ($ 0,39 per minuut). In een abonnement daalt de werkelijke minuutprijs: ongeveer $ 0,28 met Receptionist, $ 0,25 met Assistent en $ 0,22 met Callcenter, dus ongeveer $ 1,10 tot $ 1,40 voor hetzelfde gesprek.' },
];
